version: '2.0'
services:
  server:
    build: .
    volumes:
      - .:/code
    ports:
      - "5000:5000"
    working_dir: /code
    environment:
      - FLASK_APP=server
    command: flask run -h 0.0.0.0 -p 5000